app:
  name: identity-service

  # database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_identity?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: password
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

entitymanager:
  packagesToScan: com.pos

lockuser:
  invalidcount: 3

jwt:
  secret: $SqQE=YFFGFHA&RF3__=rzT2*H98M#e!j&ef=v%x?@@_$%_ts%

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    #    eureka-service-url-poll-interval-seconds: 0
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
 
inventory-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:5000       
#skip feign clients through eureka    
#bankingcore-identity:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    listOfServers: http://localhost:6003  

