app:
  name: shopping-service
#database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

    tomcat:
      initial-size: 10
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 5
    #hikari:
      #connection-timeout: 120000
      #idle-timeout: 60000
      #max-lifetime: 120000
      #minimum-idle: 2
      #maximum-pool-size: 4   
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB      
        
entitymanager:
  packagesToScan: com.companycore

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    #    eureka-service-url-poll-interval-seconds: 0
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
        
