app:
  name: discovery-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: communication-service
#          uri: http://localhost:6002/
#          predicates:
#            -Path=/v1/communication/**
        - id: pos-service
          uri: http://127.0.0.1:6003/
          predicates:
            - Path=/pos/**
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true       

eureka:
  instance:
    hostname: ${EUREKA_SERVICE}
  client:
    registerWithEureka: true
    fetchRegistry: true
    #    eureka-service-url-poll-interval-seconds: 0
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/


feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000